domain_path: C:\sp24-ece520-freertos-kria-stevenhernandezz\software\kr260_platform\export\kr260_platform\sw\freertos_psu_cortexa53_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
